services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: import_airports_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: import_airports_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes: {}
