# Generated by Django 5.2.7 on 2025-10-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['iata'],
            },
        ),
        migrations.CreateModel(
            name='ImportLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('airports_created', models.PositiveIntegerField(default=0)),
                ('airports_updated', models.PositiveIntegerField(default=0)),
                ('created_iatas', models.JSONField(default=list, help_text='List of IATA codes for newly created airports.')),
                ('updated_iatas', models.JSONField(default=list, help_text='List of IATA codes for updated airports.')),
                ('details', models.TextField(blank=True, help_text='Contains error messages or other details.')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
